#!/usr/bin/bash

if [[ ! -v ZETTEL_DIR ]]; then
    echo "$(basename $0): $ZETTEL_DIR is not set"
    exit 1
fi

azfile=$ZETTEL_DIR/auto/all-zettel.dat

shopt -s globstar
cd $ZETTEL_DIR
cat **/*.txt > $azfile
