#!/usr/bin/bash
# Fix the links from <old> to <new>

old=
new=
if [[ $# -eq 2 ]]; then
    old="$1"
    new="$2"
else
    echo "Usage: zchangelinks <from> <to>"
    exit 1
fi

while IFS= read -r file
do
    # This matches both the numerus currens and ISO-8601 date
    if [[ -e $file && "${file##*/}" =~ ^[0-9]{3} ]]; then
        echo "zchangelinks: Fixing $file..."
        sed -i -e "s/\([[|:]\)$old]]/\1$new]]/g" $file
    elif [[ ! "$file" ]]; then
        :                       # bash equivalent of NOP
    else
        echo "zchangelinks: File '$file' doesn't appear valid: skipping"
    fi
done
