#!/usr/bin/bash
# Fix the links from <old> to <new>

old=
new=
if [[ $# -eq 2 ]]; then
    old="$1"
    new="$2"
else
    echo "Usage: zfixlink <old> <new>"
    exit 1
fi

while IFS= read -r file
do
    # This matches both the numerus currens and ISO-8601 date
    if [[ -e $file && "${file##*/}" =~ ^[0-9]{3} ]]; then
        echo "zfixlink: Fixing $file..."
        sed -i -e "s/\([[|]\)$old]]/\1$new]]/g" $file
    else
        echo "zfixlink: File $file doesn't appear valid: skipping"
    fi
done
