#!/bin/bash
# Fix the timestamps and commit with default commit string

if [[ -z "$ZETTEL_DIR" ]]; then
    echo "$(basename $0): $ZETTEL_DIR is not set"
    exit 1
fi

# Copy files from ~/Dropbox/Apps/Orgzly
zorgzly

# Fix times and commit
cd $ZETTEL_DIR

# Get rid of extraneous files
find ./ -name "*.html" -or -name "*.odt" -exec rm -i {} \;

hg addremove
modified=$(hg status --modified | wc -l | awk '{ print $1 }')
removed=$(hg status --removed | wc -l | awk '{ print $1 }')
added=$(hg status --added | wc -l | awk '{ print $1 }')
unknown=$(hg status --unknown | wc -l | awk '{ print $1 }')

output=""
if [ $modified -gt 0 ]; then
    output="${output}${output:+, }${modified} modified"
fi
if [ $removed -gt 0 ]; then
    output="${output}${output:+, }${removed} removed"
fi
if [ $added -gt 0 ]; then
    output="${output}${output:+, }${added} added"
fi
if [ $unknown -gt 0 ]; then
    output="${output}${output:+, }${unknown} unknown"
fi

zfixtimes
hg commit -e -m "$output"
