#!/usr/bin/bash
# Outputs the date name (YYYYMMDDThhmm) for the given file, combining the
# created date with time of last modification

fname=$1
bname=$(basename $fname)
ext=${bname#*.}

created=`grep '^created:' $fname`
if [[ $created =~ created:.+([0-9]{4})-([0-9]{2})-([0-9]{2}) ]]; then
    year=${BASH_REMATCH[1]}
    month=${BASH_REMATCH[2]}
    day=${BASH_REMATCH[3]}

    modified=$(date -d @$(stat -c'%Y' "$@") "+%H%M")
    if [[ $modified != "" ]]; then
        echo "${year}${month}${day}T${modified}.$ext"
    else
        echo "No modification time"
        exit 1
    fi
else
    echo "No created date"
    exit 1
fi
    
