#!/usr/bin/env ruby
# Figure out the right directory for the given numerus currens

require 'clamp'
require_relative 'zettel'

Clamp do
  parameter "NUMERUS_CURRENS", "numerus currens to get directory for",
            :attribute_name => :numcur

  def execute
    puts Numerus.new(numcur).directory
  end
end
