#!/usr/bin/env ruby
# Prints the full path for the given numerus currens

require 'clamp'
require_relative 'zettel'

Clamp do
  parameter "NUMERUS_CURRENS", "numerus currens to get directory for",
            :attribute_name => :numcur

  def execute
    puts Zettelkasten.dir("main") + Numerus.section_of(numcur) + (numcur + Zettelkasten.ext)
  end
end
