#!/usr/bin/bash
# Find all Zettel with names beginning with the given string

if [[ ! -v ZETTEL_DIR ]]; then
    echo "$(basename $0): $ZETTEL_DIR is not set"
    exit 1
fi

cd $ZETTEL_DIR
find ./ -type f -name "$1*.txt" | sed -e 's!^\./!!' | sort
