#!/bin/bash
# Generates the frequency file

if [[ ! -v ZETTEL_DIR ]]; then
    echo "$(basename $0): $ZETTEL_DIR is not set"
    exit 1
fi

allzettel="$ZETTEL_DIR/auto/all-zettel.dat"
freqfile="$ZETTEL_DIR/auto/word-frequency.dat"
excludefile=/tmp/all-zettel.$$.exclude

# Exclude the metadata keywords and common section names
cat > $excludefile <<EOF
created
title
modified
oldname
readings
summary
notes
connections
EOF

# Create frequency file if it doesn't exist
if [[ ! -e $freqfile ]]; then
    touch $freqfile
fi

# Check that $allzettel file exists
if [[ ! -e $allzettel ]]; then
    echo "Error: No all-zettel file ($allzettel); run zcatall and rerun"
    exit 1
fi

# Doesn't do Unicode very well
# tr -c '[:alnum:]' '[\n*]' < $1 | awk 'NF'

# Replace all special symbols with space to prevent them confusing zwf
sed -r -e 's/[.,:;?!(){}:@«»*"#\/_”`|]/ /g' -e 's/\[/ /g' -e 's/\]/ /g' < $allzettel |
    sed -e 's/\s/\n/g' |
    tr '[:upper:]' '[:lower:]' |
    grep -E '.{3}' |            # matches only words of 3+ characters
    fgrep -v -w -f $excludefile |
    sort | uniq -c | sort -nr | sed -re 's/\s+//' > $freqfile

# Cleanup
rm -f $excludefile

