#!/usr/bin/env ruby
# Rename Zettel to date/time and move it into limbo

require 'clamp'
require_relative 'zettel'

Clamp do
  parameter "SLUG", "slug of the Zettel to move to limbo"
  option ["-t", "--time"], "HHMM", "use the specified time", :attribute_name => :use_time

  def execute
    puts "--- Zettel beginning with #{slug}: ---"
    system("zfind", "#{slug}")
    puts ""

    if use_time
      datename = `zdatename -t #{use_time} #{slug}`
    else
      datename = `zdatename ${slug}`
    end

    system("zmove", slug, "limbo:#{datename}")
  end
end
