#!/bin/bash

usage() {
    echo "zlinksto <slug> -- find all zettel containing <slug>]]"
    exit 0
}

if [[ ! -v ZETTEL_DIR ]]; then
    echo "$(basename $0): $ZETTEL_DIR is not set"
    exit 1
fi

cd $ZETTEL_DIR
grep --include='*.txt' -lRE "[:|[]${1}]]" *
