#!/usr/bin/env ruby
# List zettel with wiki links to the given slug

require 'clamp'
require_relative 'zettel'

Clamp do
  parameter "SLUG", "slug to find links to", :attribute_name => :slug

  def execute
    Dir.chdir(Zettelkaesten.root)
    system("grep --include=*#{Zettelkaesten.ext} -lER '[:|[]#{slug}]]' *")
  end
end
