#!/bin/bash
# Easy way to rename zettel files; relies on ~/bin/zdatename

if [[ -z "$ZETTEL_DIR" ]]; then
    echo "$(basename $0): $ZETTEL_DIR is not set"
    exit 1
fi

limbodir=$ZETTEL_DIR/limbo
techdir=$ZETTEL_DIR/tech
personaldir=$ZETTEL_DIR/personal
writingdir=$ZETTEL_DIR/writing

function usage() {
    echo "Usage: zmakedate [-t <HHMM>] [-m ...] [-n] [-r] <slug>"
    echo "  -t|--time <HHMM> -- use the given time"
    echo "  -m|--move limbo|tech|personal|writing -- move to the designated sub-kasten"
    echo "  -n|--rename -- "
    echo "  -r|--retouch -- retouch"
    echo "  -h|--help -- show this message"
}

if [[ $# -eq 0 ]]; then
    usage
    exit 1
fi

moveto="."
fname=
time=
rename=
retouch=
origmodtime=
while [ "$1" != "" ]; do
    case $1 in
        -m | --move )
            shift
            if [[ "$1" == "limbo" ]]; then
                moveto=$limbodir
            elif [[ "$1" == "tech" ]]; then
                moveto=$techdir
            elif [[ "$1" == "personal" ]]; then
                moveto=$personaldir
            elif [[ "$1" == "writing" ]]; then
                moveto=$writingdir
            else
                echo "Error: Unknown move destination ($1); giving up"
                exit 1
            fi
            ;;
        -t | --time )
            shift
            time=$1
            ;;
        -r | --retouch )
            retouch=1
            ;;
        -n | --rename )
            rename=1
            ;;
        -h | --help )
            usage
            exit
            ;;
        * )
            if [[ -e "$1" ]]; then
                fname="$1"
                origmodtime=$(stat -c'%Y' "$fname")
            else
                fname="$(zdirectory ${1})/${1}.txt"
                fname="${fname##$ZETTEL_DIR/}"
                if [[ ! -e "$fname" ]]; then
                    echo "Error: File '$1' does not exist"
                    usage
                    exit 1
                fi
            fi
    esac
    shift
done

if [[ "$time" ]]; then
    #
    # If time is provided, only try that one, and give up if it exists.
    #
    datename=$(zdatename -t "$time" "$fname")
    if [[ -e "$moveto/$datename" ]]; then
        echo "Error: Note `$moveto/$datename` already exists"
        exit 1
    fi
else
    #
    # Otherwise, try the time of last modification, the time of last status
    # change, and just 00:00.
    #
    datename=$(zdatename -m "$fname")
    if [[ -e "$moveto/$datename" ]]; then
        datename=$(zdatename -c "$fname")
        if [[ -e "$moveto/$datename" ]]; then
            datename=$(zdatename -z "$fname")
            if [[ -e "$moveto/$datename" ]]; then
                echo "Error: Can't move $fname because all attempted datenames already exist."
                exit 1
            fi
        fi
    fi
fi

# Move the file and fix references to it
zmove "$fname" "$moveto/$datename"

if [[ $? -eq 0 && "$retouch" ]]; then
    touch -d"@$origmodtime" "$moveto/$datename"
fi
