#!/usr/bin/python
import argparse
import subprocess
import os

# Parse command line arguments
parser = argparse.ArgumentParser(description='Move an entire branch of zettel')
parser.add_argument('source', help='Branch to move from (a numerus currens)')
parser.add_argument('target', help='Where to move to (a numerus currens)')
args = parser.parse_args()

# Get list of matching zettel
files = subprocess.check_output(["zfind", args.source]).decode('ascii').splitlines()
files.sort()

# Give user chance to back out
print('\n'.join(files))
input('Press [Enter] to continue moving these under {:s}...'.format(args.target))

# Move those zettels
for file in files:
    old_slug = os.path.splitext(os.path.basename(file))[0]
    new_slug = old_slug.replace(args.source, args.target)
    print('Moving {:s} to {:s}:\n'.format(old_slug, new_slug))

    subprocess.run(['zmove', old_slug, new_slug])
    print('----------------------------------------')
