#!/usr/bin/env ruby
# Move an entire Zettel branch

require 'clamp'
require_relative 'zettel'

Clamp do
  parameter "SOURCE", "branch to move from (a numerus currens)"
  parameter "TARGET", "where to move to (a numerus currens)"

  def execute
    # Get list of matching zettel
    files = `zfind #{source}`.split("\n").sort

    # Give user chance to back out
    puts files
    puts "Press [Enter] to continue moving these under #{target}..."
    STDIN.gets

    # Move those zettels
    files.each do |file|
      old_slug = File.basename(file, Zettelkaesten.ext)
      new_slug = old_slug.gsub(source, target)
      puts "Moving #{old_slug} to #{new_slug}"
      #system("zmove", old_slug, new_slug)
    end
  end
end
