#!/bin/bash
# Fix the timestamps and commit with default commit string

if [[ -z "$ZETTEL_DIR" ]]; then
    echo "$(basename $0): $ZETTEL_DIR is not set"
    exit 1
fi

modified=$(date "+%Y-%m-%d")

study=20180727T1421.txt
todo=20190514T1925.txt
fate=20180802T2002.txt
mouse=20191026T1954.txt

cd $HOME/Dropbox/Apps/Orgzly
echo "Pulling files from Apps/Orgzly..."
sed -e "s/^modified:.*$/modified: ${modified}/" study.org > $ZETTEL_DIR/limbo/$study
sed -e "s/^modified:.*$/modified: ${modified}/" todo.org > $ZETTEL_DIR/limbo/$todo
sed -e "s/^modified:.*$/modified: ${modified}/" mouse.org > $ZETTEL_DIR/rp/$mouse
sed -e "s/^modified:.*$/modified: ${modified}/" fate.org > $ZETTEL_DIR/rp/$fate
echo "Done"
