#!/bin/bash

# Change the file modification time based on either its timestamped filename or
# based on the information inside the file.

if [ $# -eq 1 ]; then
    file=$1
    filetop=$(head -4 $file)

    # Prefer modification date in the file, followed by timestamped filename,
    # followed by creation date in the file.
    if [[ "$filetop" =~ modified:[[:space:]]+([0-9-]{10}) ]]; then
        time="${BASH_REMATCH[1]}"
        echo "$file: $time";
    elif [[ "$file" =~ ([0-9]{8})T([0-9]{4}) ]]; then
        time="${BASH_REMATCH[1]} ${BASH_REMATCH[2]}"
        echo "$file: $time"
    elif [[ "$filetop" =~ created:[[:space:]]+([0-9-]{10}) ]]; then
        time="${BASH_REMATCH[1]}"
        echo "$file: $time";
    else
        echo "$file: Cannot determine modification date";
        time=""
    fi

    if [[ "$time" != "" ]]; then
        touch -d "$time" $file;
    fi
else
    echo "Usage: $(basename $0) <filename>"
    exit 2
fi
