#!/bin/bash
# Get timestamp for the given Zettel file

if [[ -z "$ZETTEL_DIR" ]]; then
    echo "$(basename $0): $ZETTEL_DIR is not set"
    exit 1
fi

tsfile="$ZETTEL_DIR/.hgtimestamp"
timestamp=$(grep '["/]'"$1\.txt" $tsfile | grep -oE '[0-9]{10}\.[0-9]+')
date -r ${timestamp%%.0} "+%Y-%m-%d %H:%M"
