#!/usr/bin/bash
# Move the limbo file to the Zettel in its proper directory

function usage() {
    echo "Usage: zunlimbo <file in limbo> <numerus currens>"
    exit 1
}

if [[ ! -v ZETTEL_DIR ]]; then
    echo "$(basename $0): $ZETTEL_DIR is not set"
    exit 1
fi

limbodir=$ZETTEL_DIR/limbo
maindir=$ZETTEL_DIR/main
defaultext="txt"

# Have to be in $ZETTEL_DIR, otherwise Mercurial could complain about nested repos
cd "$ZETTEL_DIR"

numcur="${2%%.*}"
file="$1"
ext=${file##*.}
ext=${ext:-$defaultext}
if [[ $# -ne 2 ]]; then
    usage
elif [[ ! -e $file ]]; then
    file="$limbodir/$1.$ext"
    ext=$ext
    if [[ ! -e $file ]]; then
        usage
    fi
fi

rightdir=$(zdirectory $numcur)

# Move the file and fix references to it
zmove "$fname" "$moveto/$datename"

echo "hg mv $file $rightdir/$numcur.$ext"
move=$(hg mv $file $rightdir/$numcur.$ext)
if [[ $? -eq 0 ]]; then
    # Succcess
    echo "Moved $file to $rightdir/$numcur.$ext"
elif [[ $? -eq 255 ]]; then
    # File untracked, revert to normal move
    mv $file $rightdir/$numcur.$ext;
    echo "Moved $file to $rightdir/$numcur.$ext"
else
    # Unexpected
    echo "Unexpected failure from hg mv: $?\n$move"
fi
