#!/usr/bin/bash
# Move the limbo file to the Zettel in its proper directory

ZETTELDIR="$HOME/Dropbox/Doc/zettel"
LIMBODIR="$ZETTELDIR/limbo"
MAINDIR="$ZETTELDIR/main"
DEFAULTEXT="txt"

function usage() {
    echo "Usage: zunlimbo <file in limbo> <numerus currens>"
    exit 1
}    

# Have to be in $ZETTELDIR, otherwise Mercurial could complain about nested repos
cd "$ZETTELDIR"

numcur="${2%%.*}"
file="$1"
ext=${file##*.}
if [[ $# -ne 2 ]]; then
    usage
elif [[ ! -e $file ]]; then
    file="$LIMBODIR/$1.$DEFAULTEXT"
    ext=$DEFAULTEXT
    if [[ ! -e $file ]]; then
        usage
    fi
fi

rightdir=$(zdirectory $numcur)

echo "hg mv $file $rightdir/$numcur.$ext"
move=$(hg mv $file $rightdir/$numcur.$ext)
if [[ $? -eq 0 ]]; then
    # Succcess
    echo "Moved $file to $rightdir/$numcur.$ext"
elif [[ $? -eq 255 ]]; then
    # File untracked, revert to normal move
    mv $file $rightdir/$numcur.$ext;
    echo "Moved $file to $rightdir/$numcur.$ext"
else
    # Unexpected
    echo "Unexpected failure from hg mv: $?\n$move"
fi
