#!/bin/zsh
# Fix the timestamps and commit with default commit string

if [[ -z "$ZETTEL_DIR" ]]; then
    echo "$(basename $0): $ZETTEL_DIR is not set"
    exit 1
fi

# Copy files from ~/Dropbox/Apps/Orgzly
#zorgzly

cd $ZETTEL_DIR

# Get rid of extraneous files (maxdepth needed to exclude **/files/)
#find ./ -maxdepth 2 -name "*.html" -or -name "*.docx" -exec rm -i {} \;
#find main/ -maxdepth 2 -name "*.html" -or -name "*.docx" -exec rm -i {} \;

echo "Adding all TXT, BIB, and SCAP files..."
git add **/*.txt **/*.bib **/*.scap

modified=$(git status --short | grep -c '^M')
deleted=$(git status --short | grep -c '^D')
added=$(git status --short | grep -c '^A')
renamed=$(git status --short | grep -c '^R')

output=""
if [ $modified -gt 0 ]; then
    output="${output}${output:+, }${modified} modified"
fi
if [ $renamed -gt 0 ]; then
    output="${output}${output:+, }${renamed} renamed"
fi
if [ $deleted -gt 0 ]; then
    output="${output}${output:+, }${deleted} deleted"
fi
if [ $added -gt 0 ]; then
    output="${output}${output:+, }${added} added"
fi
echo $output

#echo $output > /tmp/zcommit.$$
#
#zfixtimes
#git commit --template=/tmp/zcommit.$$
#if [ $? -eq 0 ]; then
#    rm -f /tmp/zcommit.$$
#fi
