#!/usr/bin/env ruby
# coding: utf-8
# List zettel with wiki links to the given ID

require 'clamp'
require 'open3'
require_relative 'zettel'

Clamp do
  parameter "ID", "id to find links to", :attribute_name => :id
  option ["-p", "--pprint"], :flag, "pretty print", :attribute_name => :pretty_print

  def execute
    format_string = "%-13s  %-10s  %s"

    if pretty_print?
      puts format_string % ["ID", "Kasten", "Title"]
      puts format_string % ["----", "------", "-----"]
    end

    zettel = Zettel.new_from_link(id)
    zettel.links_to.each do |z|
      if pretty_print?
        just_title = z.metadata[:title].gsub(/§[^.]+\. /, "")
        puts format_string % [z.id, z.kasten, just_title]
      else
        puts z.link
      end
    end
  end
end
