#!/bin/bash
# Returns the next numerus from unused-numeri.dat

if [[ -z "$ZETTEL_DIR" ]]; then
    echo "$(basename $0): $ZETTEL_DIR is not set"
    exit 1
fi
unused_numeri=$ZETTEL_DIR/auto/unused-numeri.dat

head -n1 "$unused_numeri"
sed -i '' -e '1d' "$unused_numeri"

