#!/bin/bash
# Fix the timestamps and commit with default commit string

if [[ -z "$ZETTEL_DIR" ]]; then
    echo "$(basename $0): $ZETTEL_DIR is not set"
    exit 1
fi

modified=$(date "+%Y-%m-%d %a %H:%I")

study=$ZETTEL_DIR/os/2018/os:20180727T1421.txt
todo=$ZETTEL_DIR/os/2019/os:20190514T1925.txt

cd /Volumes/User/Dropbox/Apps/Orgzly
echo "Pulling study.org and todo.org from Apps/Orgzly..."

sed -e "s/^modified:.*$/modified: ${modified}/" study.org > $study
sed -e "s/^modified:.*$/modified: ${modified}/" todo.org > $todo

echo "Done"
