#!/usr/bin/env ruby
# Does a zlinksto for the ID, and deletes it after confirmation

require 'clamp'
require_relative 'zettel'

Clamp do
  parameter "ID", "ID to remove", :attribute_name => :id
  option ["-v", "--verbose"], :flag, "verbose", :attribute_name => :verbose
  option ["-i", "--interactive"], :flag, "interactive", :attribute_name => :interactive

  def execute
    zettel = Zettel.new_from_link(id)

    puts "The following notes have links to #{zettel.link}:"
    Dir.chdir(Zettelkasten.root)
    system("zlinksto #{id}")

    # Give user chance to interrupt
    puts "zremove: Press [Enter] to remove #{zettel.link}..."
    STDIN.gets

    # Replace links to note with those to its parent
    grandparent = zettel.metadata[:parent]
    zettel.links_to().each do |z|
      if /#{zettel.link}/ =~ z.metadata[:parent]
        STDERR.puts "Replacing #{z.link}'s parent with #{grandparent}"
        z.metadata[:parent] = grandparent
      end

      if grandparent
        z.replace_links(zettel.link, grandparent)
      else
        removed = z.remove_links(zettel.link)
        STDERR.puts "Removed #{removed} links in #{z.link}"
      end

      z.write_file
    end

    # Remove the file
    system("git rm -f #{zettel.relative_path}")
    if $?.exitstatus != 0
      STDERR.puts "Git could not remove the file; aborting"
      exit(1)
    end
  end
end
