#!/bin/bash
# Change the file modification time based on either its timestamped filename or
# based on the information inside the file.

do_retouch () {
    file="$1"
    filetop=$(head -4 "$file")

    # Prefer modification date in the file followed by creation date in the
    # file.
    curtime=$(date +%H%M)
    if [[ "$filetop" =~ modified:[[:space:]]+([0-9-]{10}) ]]; then
        date="${BASH_REMATCH[1]//-/}"
        time=$curtime
        echo "$file: modified on ${date}${time}";
    elif [[ "$file" =~ ([0-9]{8})T([0-9]{4}) ]]; then
        date="${BASH_REMATCH[1]}"
        time="${BASH_REMATCH[2]}"
        echo "$file: ISO8601 filename: ${date}T${time}"
    elif [[ "$filetop" =~ created:[[:space:]]+([0-9-]{10}) ]]; then
        date="${BASH_REMATCH[1]//-/}"
        time=$curtime
        echo "$file: created on ${date}${time}";
    else
        echo "$file: Cannot determine modification or creation time";
        date=""
        time=""
    fi

    if [[ "$date" != "" ]]; then
        touch -t "${date}${time}" "$file";
        if [ $? -ne 0 ]; then
            echo "Errored with this command: touch -t '${date}${time}' $file;"
        fi
    fi
}

for file in "$@";
do
    if [ -f "$file" ]; then
        do_retouch "$file"
    else
        echo "Usage: $(basename $0) <filename(s)>"
        exit 2
    fi
done
