#!/bin/zsh

modified=$(git status --short | grep -c '^M')
deleted=$(git status --short | grep -c '^D')
added=$(git status --short | grep -c '^A')
renamed=$(git status --short | grep -c '^R')

output=""
if [ $modified -gt 0 ]; then
    output="${output}${output:+, }${modified} modified"
fi
if [ $renamed -gt 0 ]; then
    output="${output}${output:+, }${renamed} renamed"
fi
if [ $deleted -gt 0 ]; then
    output="${output}${output:+, }${deleted} deleted"
fi
if [ $added -gt 0 ]; then
    output="${output}${output:+, }${added} added"
fi
echo $output
