#!/usr/bin/env ruby
# Returns the ID type of the given Zettel: either 'numerus' or 'tempus'

require 'clamp'
require_relative 'zettel'

Clamp do
  parameter "PATH", "the path to Zettel for which to return the type",
            :attribute_name => :path

  def execute
      puts Zettelkasten.id_type_of(path)
  end
end
