#!/usr/bin/env ruby

require 'clamp'
require_relative 'zettel'

Clamp do
  def execute
    # Need to get rid of ARGV arguments before ARGF.each_line starts reading
    # from STDIN
    until ARGV.empty? do
      ARGV.shift
    end

    # Get the list of new IDs
    new_ids_file = "/Users/richard/Dropbox/Zettel/auto/new-ids"
    new_ids = File.readlines(new_ids_file).each {|line| line.chomp!}
    used_ids = Array.new

    # Read list of files to replace the links in from STDIN
    ARGF.each_line do |line|
      line = line.strip

      if !line.empty?
        old = Zettel.new_from_link(line)

        used_ids.push("#{old.id} => #{new_ids.last}")
        new = Zettel.new_from_link(new_ids.pop)

        while new.exists?
          puts "Warning: Zettel #{new.id} exists; skipping"
          new = Zettel.new_from_link(new_ids.pop)
        end

        # Check that the file exists and is either a numerus currens or datetime
        if old
          system("zmove", old.id, new.id)
        else
          STDERR.puts "Error: File '#{line}' doesn't appear valid; skipping"
        end
      end
    end

    puts "Writing remaining unused ids back..."
    File.open(new_ids_file, "w") do |f|
      f.puts(new_ids)
    end

    puts "Saving used ids..."
    used_ids_file = "/Users/richard/Dropbox/Zettel/auto/used-new-ids"
    File.open(used_ids_file, "a") do |f|
      f.puts(used_ids)
    end
  end
end
